#!/bin/bash

Path='/usr/bin/'
LogPath='/usr/log'

if [ $1 == 'start' ]
then

cd ${Path} && sudo nohup  ./restartMonitor.sh /etc/deepdefense/deepdefense-monitor-rules.yaml ./md5file > ${Path}/output 2>&1 &

exit 0
fi

if [ $1 == 'stop' ]
then
Data=$(ps -ax | grep -E 'restartMonitor'|awk '{print $1}')
array_ID=($Data)
for ID in ${array_ID[@]}
do
  echo $ID
  sudo kill $ID
done
echo 'stop already'

exit 0
fi

if [ $1 == 'restart' ]
then
./deepsphere stop
./deepsphere start
exit 0
fi
